const deepFreeze = (value) => {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.values(value).forEach(deepFreeze);
  return Object.freeze(value);
};

/**
 * Central gameplay tuning. Systems should read from this object instead of
 * embedding balance numbers in render or input code.
 */
export const GAME_CONFIG = deepFreeze({
  version: 1,
  seed: "sin-city-rp-2026",
  world: {
    size: 760,
    halfSize: 380,
    groundY: 0,
    blockSize: 52,
    roadWidth: 16,
    avenueWidth: 24,
    casinoDistrictRadius: 165,
    airport: { x: -270, z: 245, width: 150, length: 230, runwayWidth: 28 },
    tunnel: {
      floorY: -12,
      ceilingY: -5,
      width: 15,
      accessRadius: 4.5,
      floodSlowdown: 0.72,
      lootMultiplier: 1.65,
    },
    population: {
      pedestrians: 38,
      traffic: 22,
      parkedVehicles: 16,
      pickups: 34,
      tunnelPickups: 12,
    },
  },
  time: {
    dayLengthSeconds: 720,
    startHour: 21,
    casinoLightsOnHour: 17.5,
    casinoLightsOffHour: 7,
  },
  player: {
    maxHealth: 100,
    maxArmor: 100,
    startHealth: 100,
    startArmor: 15,
    startCash: 750,
    startCasinoChips: 100,
    startAmmo: 54,
    height: 2.15,
    radius: 0.42,
    walkSpeed: 5.4,
    runSpeed: 9.2,
    crouchSpeed: 2.8,
    jumpImpulse: 7.2,
    airControl: 0.25,
    turnSpeed: 10,
    healthRegenDelay: 12,
    healthRegenPerSecond: 1.5,
  },
  camera: {
    onFootDistance: 8.5,
    vehicleDistance: 13,
    planeDistance: 22,
    minPitch: -0.18,
    maxPitch: 0.92,
    lookSensitivity: 0.0024,
    followSharpness: 8,
  },
  physics: {
    gravity: 19.6,
    terminalVelocity: 48,
    groundFriction: 10,
    collisionSkin: 0.08,
    fixedStep: 1 / 60,
    maxFrameDelta: 0.05,
  },
  interaction: {
    distance: 3.25,
    vehicleEnterDistance: 3.6,
    pickupDistance: 1.75,
    cooldownSeconds: 0.45,
    persuasion: {
      baseChance: 0.44,
      minChance: 0.08,
      maxChance: 0.9,
      charismaWeight: 0.028,
      trustWeight: 0.004,
      fearWeight: 0.002,
      heatPenaltyPerLevel: 0.055,
      retryPenalty: 0.12,
      trustGainOnSuccess: 12,
      trustLossOnFailure: 9,
    },
    bribe: {
      baseAmount: 120,
      heatMultiplier: 1.55,
      copMultiplier: 2.25,
      tunnelDiscount: 0.82,
      minSuccessChance: 0.12,
      maxSuccessChance: 0.92,
      overpayBonusCap: 0.32,
      failureHeat: 8,
    },
  },
  combat: {
    meleeDamage: 12,
    meleeRange: 1.75,
    meleeCooldown: 0.62,
    armorAbsorption: 0.65,
    headshotMultiplier: 1.65,
    tracerLifetime: 0.075,
    civilianDamageHeat: 16,
    policeDamageHeat: 28,
  },
  crime: {
    maxHeat: 100,
    wantedThresholds: [0, 15, 32, 52, 74, 92],
    heatDecayDelay: 10,
    heatDecayPerSecond: 1.35,
    hiddenDecayMultiplier: 2.1,
    witnessRadius: 34,
    reportDelaySeconds: 2.4,
    heatByOffense: {
      weaponDischarge: 6,
      assault: 14,
      vehicleTheft: 17,
      casinoCheating: 20,
      robbery: 26,
      policeAssault: 34,
    },
  },
  police: {
    responseDelaySeconds: 4,
    maxActiveByWantedLevel: [0, 2, 3, 5, 7, 10],
    spawnMinDistance: 38,
    spawnMaxDistance: 72,
    investigateSeconds: 11,
    loseSightSeconds: 8,
    arrestRange: 1.8,
    arrestHoldSeconds: 2.6,
    patrolSpeed: 3.2,
    chaseSpeed: 6.8,
    aimDelaySeconds: 0.8,
    shotCooldownSeconds: 0.75,
  },
  vehicle: {
    enterSeconds: 0.45,
    exitSpeedLimit: 7,
    steeringReturn: 3.6,
    rollingResistance: 0.985,
    offRoadGripMultiplier: 0.68,
    tunnelSpeedMultiplier: 0.82,
    collisionDamageScale: 0.34,
    fuelBurnPerSecond: 0.035,
  },
  plane: {
    maxHealth: 240,
    maxSpeed: 78,
    cruiseSpeed: 48,
    stallSpeed: 19,
    acceleration: 16,
    brake: 10,
    yawRate: 0.78,
    pitchRate: 0.72,
    rollRate: 1.25,
    lift: 0.0135,
    drag: 0.0048,
    landingDamageSpeed: 10,
    runwayTakeoffSpeed: 31,
    dimensions: { width: 9.4, length: 8.8, height: 2.55 },
  },
  pickups: {
    respawnSeconds: 42,
    rareRespawnSeconds: 95,
    bobHeight: 0.16,
    bobSpeed: 2.1,
    spinSpeed: 1.15,
    collectRadius: 1.7,
  },
  gambling: {
    minimumBet: 10,
    maximumBet: 500,
    cashOutFeeRate: 0.02,
    dailyCompThreshold: 1000,
    games: {
      slots: { minimumBet: 10, maximumBet: 100, houseEdge: 0.085, jackpotMultiplier: 25 },
      blackjack: { minimumBet: 25, maximumBet: 500, houseEdge: 0.02, blackjackPayout: 1.5 },
      roulette: { minimumBet: 20, maximumBet: 300, houseEdge: 0.0526, straightPayout: 35 },
      highLow: { minimumBet: 10, maximumBet: 250, houseEdge: 0.04, winMultiplier: 1.92 },
    },
  },
  economy: {
    hospitalFee: 350,
    impoundFee: 225,
    ammoPrice: 3,
    armorPrice: 450,
    fuelPricePerUnit: 4,
    fenceSaleMultiplier: 0.58,
  },
});

export const ROLE_CONFIG = deepFreeze({
  drifter: {
    id: "drifter",
    label: "Desert Drifter",
    description: "Balanced survival skills and better odds when searching tunnel caches.",
    color: 0x33d6ff,
    bonuses: { tunnelLoot: 0.2, stamina: 0.08, persuasion: 0 },
    starting: { cash: 650, chips: 75, weapon: "pistol", vehicle: "compact" },
  },
  hustler: {
    id: "hustler",
    label: "Strip Hustler",
    description: "A silver tongue, cheaper bribes, and stronger casino comps.",
    color: 0xff3da5,
    bonuses: { persuasion: 0.12, bribeDiscount: 0.15, casinoComps: 0.2 },
    starting: { cash: 900, chips: 150, weapon: "pistol", vehicle: "sedan" },
  },
  wheelman: {
    id: "wheelman",
    label: "Wheelman",
    description: "Sharper handling and less collision damage in ground vehicles.",
    color: 0xffb21c,
    bonuses: { vehicleHandling: 0.14, collisionResistance: 0.12, repairDiscount: 0.1 },
    starting: { cash: 500, chips: 50, weapon: "smg", vehicle: "muscle" },
  },
  highRoller: {
    id: "highRoller",
    label: "High Roller",
    description: "Starts flush and earns faster trust with casino staff and VIPs.",
    color: 0xf4d35e,
    bonuses: { vipTrust: 18, casinoComps: 0.35, intimidationPenalty: 0.08 },
    starting: { cash: 1600, chips: 400, weapon: "pistol", vehicle: "sports" },
  },
  pilot: {
    id: "pilot",
    label: "Dust Devil Pilot",
    description: "Improved aircraft control and safer hard landings.",
    color: 0x9d8cff,
    bonuses: { planeControl: 0.16, stallRecovery: 0.18, landingResistance: 0.25 },
    starting: { cash: 550, chips: 50, weapon: "pistol", vehicle: "suv" },
  },
});

export const WEAPONS = deepFreeze({
  unarmed: {
    id: "unarmed",
    label: "Fists",
    damage: 12,
    fireRate: 1.6,
    range: 1.75,
    spread: 0,
    magazineSize: 0,
    reloadSeconds: 0,
    noise: 2,
    heat: 4,
    tracerColor: 0xffffff,
    price: 0,
  },
  pistol: {
    id: "pistol",
    label: "9mm Pistol",
    damage: 24,
    fireRate: 4.2,
    range: 66,
    spread: 0.018,
    magazineSize: 15,
    reserveAmmo: 45,
    reloadSeconds: 1.35,
    noise: 22,
    heat: 7,
    tracerColor: 0xffd36a,
    price: 480,
  },
  smg: {
    id: "smg",
    label: "Compact SMG",
    damage: 15,
    fireRate: 11,
    range: 54,
    spread: 0.04,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadSeconds: 1.7,
    noise: 30,
    heat: 9,
    tracerColor: 0xffbf42,
    price: 1250,
  },
  shotgun: {
    id: "shotgun",
    label: "Pump Shotgun",
    damage: 11,
    pellets: 8,
    fireRate: 1.15,
    range: 32,
    spread: 0.09,
    magazineSize: 6,
    reserveAmmo: 24,
    reloadSeconds: 2.45,
    noise: 44,
    heat: 12,
    tracerColor: 0xff8d35,
    price: 1750,
  },
  taser: {
    id: "taser",
    label: "Stun Device",
    damage: 3,
    stunSeconds: 4.5,
    fireRate: 0.7,
    range: 12,
    spread: 0.012,
    magazineSize: 1,
    reserveAmmo: 8,
    reloadSeconds: 1.8,
    noise: 5,
    heat: 2,
    tracerColor: 0x55d9ff,
    price: 900,
  },
  goldenPistol: {
    id: "goldenPistol",
    label: "Golden Pistol",
    damage: 0,
    fireRate: 3.6,
    range: 82,
    spread: 0.008,
    magazineSize: 12,
    reserveAmmo: 72,
    reloadSeconds: 1.2,
    noise: 18,
    heat: 0,
    tracerColor: 0xfff3a3,
    specialProjectile: "goldenPistol",
    price: 0,
  },
});

export const PICKUP_TYPES = deepFreeze({
  cash: {
    id: "cash",
    label: "Loose Cash",
    color: 0x55e68b,
    glowColor: 0x19ff77,
    rarity: "common",
    weight: 24,
    amount: [30, 180],
    effect: { stat: "cash", mode: "add" },
  },
  medkit: {
    id: "medkit",
    label: "First Aid Kit",
    color: 0xf4f5f7,
    glowColor: 0xff4057,
    rarity: "common",
    weight: 15,
    amount: [24, 48],
    effect: { stat: "health", mode: "restore", cap: 100 },
  },
  armor: {
    id: "armor",
    label: "Body Armor",
    color: 0x34506d,
    glowColor: 0x45a9ff,
    rarity: "uncommon",
    weight: 9,
    amount: [25, 55],
    effect: { stat: "armor", mode: "restore", cap: 100 },
  },
  ammo: {
    id: "ammo",
    label: "Ammo Box",
    color: 0xb58a44,
    glowColor: 0xffb238,
    rarity: "common",
    weight: 18,
    amount: [12, 36],
    effect: { stat: "ammo", mode: "add" },
  },
  casinoChips: {
    id: "casinoChips",
    label: "Casino Chips",
    color: 0xe33f78,
    glowColor: 0xff4bab,
    rarity: "uncommon",
    weight: 11,
    amount: [25, 200],
    effect: { stat: "casinoChips", mode: "add" },
  },
  lockpick: {
    id: "lockpick",
    label: "Lockpick Set",
    color: 0xa8b1bd,
    glowColor: 0xd9e4ff,
    rarity: "uncommon",
    weight: 7,
    amount: [1, 2],
    effect: { stat: "lockpicks", mode: "add" },
  },
  fuel: {
    id: "fuel",
    label: "Fuel Can",
    color: 0xd63c35,
    glowColor: 0xff713f,
    rarity: "common",
    weight: 8,
    amount: [18, 35],
    effect: { stat: "vehicleFuel", mode: "restore", cap: 100 },
  },
  weaponCrate: {
    id: "weaponCrate",
    label: "Weapon Case",
    color: 0x252a32,
    glowColor: 0xa05cff,
    rarity: "rare",
    weight: 3,
    amount: [1, 1],
    lootTable: ["pistol", "smg", "shotgun", "taser"],
    effect: { stat: "weapon", mode: "unlock" },
  },
  contraband: {
    id: "contraband",
    label: "Unmarked Package",
    color: 0xc6aa72,
    glowColor: 0xffdc70,
    rarity: "rare",
    weight: 3,
    amount: [180, 650],
    effect: { stat: "fenceValue", mode: "add" },
    pickupHeat: 5,
  },
  collectible: {
    id: "collectible",
    label: "Neon Token",
    color: 0xffd64a,
    glowColor: 0xffff8b,
    rarity: "legendary",
    weight: 1,
    amount: [1, 1],
    effect: { stat: "collectibles", mode: "add" },
  },
});

export const NPC_PROFILES = deepFreeze({
  tourist: {
    id: "tourist",
    label: "Tourist",
    occupation: "visitor",
    colors: { skin: 0xd8a073, shirt: 0x47a7e8, pants: 0xd9d7cf, accent: 0xffcf4a },
    walkSpeed: 2.2,
    health: 70,
    bravery: 0.16,
    trust: 48,
    fear: 10,
    persuasionDifficulty: 0.22,
    bribe: { allowed: true, minimum: 35, greed: 0.62 },
    cash: [30, 180],
    dialogue: ["Is the Strip always this loud?", "I swear the casino was right here.", "Have you seen the fountains?"],
  },
  local: {
    id: "local",
    label: "Vegas Local",
    occupation: "resident",
    colors: { skin: 0x9a654d, shirt: 0x6f52a8, pants: 0x272d37, accent: 0x65e3c4 },
    walkSpeed: 2.6,
    health: 85,
    bravery: 0.42,
    trust: 38,
    fear: 8,
    persuasionDifficulty: 0.4,
    bribe: { allowed: true, minimum: 80, greed: 0.48 },
    cash: [45, 240],
    dialogue: ["Stay out of the wash when clouds roll in.", "Locals know the shortcuts.", "Neon looks better after midnight."],
  },
  casinoDealer: {
    id: "casinoDealer",
    label: "Casino Dealer",
    occupation: "dealer",
    colors: { skin: 0xb97755, shirt: 0xf0eee9, pants: 0x15161c, accent: 0xc92d54 },
    walkSpeed: 2.1,
    health: 80,
    bravery: 0.3,
    trust: 32,
    fear: 6,
    persuasionDifficulty: 0.56,
    bribe: { allowed: true, minimum: 180, greed: 0.5 },
    cash: [80, 260],
    dialogue: ["Place your bets when you're ready.", "The house remembers good guests.", "Keep it clean at my table."],
  },
  highRoller: {
    id: "highRoller",
    label: "High Roller",
    occupation: "vip",
    colors: { skin: 0xe0ad85, shirt: 0x181b23, pants: 0x111218, accent: 0xe8c55c },
    walkSpeed: 2.35,
    health: 90,
    bravery: 0.48,
    trust: 24,
    fear: 5,
    persuasionDifficulty: 0.72,
    bribe: { allowed: true, minimum: 450, greed: 0.28 },
    cash: [500, 1800],
    dialogue: ["Money buys access, not taste.", "I don't wait in lines.", "Bring me something worth my time."],
  },
  mechanic: {
    id: "mechanic",
    label: "Mechanic",
    occupation: "mechanic",
    colors: { skin: 0x7e513b, shirt: 0x315b78, pants: 0x22272d, accent: 0xe68a34 },
    walkSpeed: 2.4,
    health: 100,
    bravery: 0.55,
    trust: 42,
    fear: 8,
    persuasionDifficulty: 0.43,
    bribe: { allowed: true, minimum: 125, greed: 0.58 },
    cash: [70, 320],
    dialogue: ["I can make anything run once.", "Keep sand out of the intake.", "Cash first, questions later."],
  },
  tunnelRunner: {
    id: "tunnelRunner",
    label: "Tunnel Runner",
    occupation: "scavenger",
    colors: { skin: 0x805440, shirt: 0x75613f, pants: 0x292725, accent: 0x9de28f },
    walkSpeed: 2.85,
    health: 95,
    bravery: 0.67,
    trust: 22,
    fear: 4,
    persuasionDifficulty: 0.61,
    bribe: { allowed: true, minimum: 210, greed: 0.74 },
    cash: [100, 420],
    dialogue: ["Keep your light low down here.", "The wash gives, and it takes.", "I know where the dry tunnels are."],
  },
  security: {
    id: "security",
    label: "Casino Security",
    occupation: "security",
    colors: { skin: 0x5e3c32, shirt: 0x202b3a, pants: 0x151b25, accent: 0xd8b24d },
    walkSpeed: 2.8,
    health: 120,
    bravery: 0.82,
    trust: 16,
    fear: 3,
    persuasionDifficulty: 0.78,
    bribe: { allowed: true, minimum: 500, greed: 0.26 },
    cash: [90, 280],
    dialogue: ["Move along.", "VIP floor is invite only.", "Don't make this difficult."],
  },
  patrolOfficer: {
    id: "patrolOfficer",
    label: "LVMPD Officer",
    occupation: "police",
    isCop: true,
    colors: { skin: 0xb47b5c, shirt: 0x263d5a, pants: 0x18283d, accent: 0xd7b64b },
    walkSpeed: 3.2,
    chaseSpeed: 6.8,
    health: 125,
    armor: 35,
    bravery: 0.9,
    trust: 8,
    fear: 1,
    persuasionDifficulty: 0.86,
    bribe: { allowed: true, minimum: 700, greed: 0.12, maxWantedLevel: 2 },
    weapon: "pistol",
    cash: [20, 90],
    dialogue: ["Stop right there.", "Hands where I can see them.", "You're free to go—for now."],
  },
  pigEnforcer: {
    id: "pigEnforcer",
    label: "Occupation Hog Enforcer",
    occupation: "occupation-police",
    faction: "reptilian-occupation",
    species: "reptilian-porcine-hybrid",
    isCop: true,
    colors: { skin: 0x8d685a, shirt: 0x40182a, pants: 0x17151a, accent: 0xff315c },
    walkSpeed: 3.35,
    chaseSpeed: 7.4,
    health: 175,
    armor: 65,
    bravery: 1,
    trust: 2,
    fear: 0,
    persuasionDifficulty: 0.94,
    bribe: { allowed: true, minimum: 1400, greed: 0.2, maxWantedLevel: 2 },
    weapon: "smg",
    cash: [80, 260],
    dialogue: ["Curfew means curfew, mammal.", "The Strip belongs to the Directorate now.", "Credits can alter my report."],
  },
  reptilianMarshal: {
    id: "reptilianMarshal",
    label: "Reptilian Occupation Marshal",
    occupation: "occupation-command",
    faction: "reptilian-occupation",
    species: "reptilian",
    isCop: true,
    colors: { skin: 0x526a49, shirt: 0x182d31, pants: 0x10171a, accent: 0x31ffc2 },
    walkSpeed: 3.5,
    chaseSpeed: 7.7,
    health: 205,
    armor: 85,
    bravery: 1,
    trust: 0,
    fear: 0,
    persuasionDifficulty: 1,
    bribe: { allowed: false, minimum: 4000, greed: 0, maxWantedLevel: 0 },
    weapon: "shotgun",
    cash: [120, 360],
    dialogue: ["Your city has been catalogued.", "Nellis is under Directorate control.", "Compliance extends your usefulness."],
  },
  nellisGuard: {
    id: "nellisGuard",
    label: "Nellis Security",
    occupation: "military-security",
    faction: "nellis-resistance",
    isCop: true,
    colors: { skin: 0x8f6049, shirt: 0x39483c, pants: 0x202a24, accent: 0xc7b86d },
    walkSpeed: 3.2,
    chaseSpeed: 6.9,
    health: 150,
    armor: 60,
    bravery: 0.97,
    trust: 10,
    fear: 1,
    persuasionDifficulty: 0.88,
    bribe: { allowed: false, minimum: 2200, greed: 0, maxWantedLevel: 0 },
    weapon: "smg",
    cash: [45, 150],
    dialogue: ["Flight line is locked down.", "Something crossed the range last night.", "Find the resistance frequency and we can talk."],
  },
  alienObserver: {
    id: "alienObserver",
    label: "Extraterrestrial Observer",
    occupation: "observer",
    faction: "groom-visitors",
    species: "extraterrestrial",
    colors: { skin: 0x879a8d, shirt: 0x1b2730, pants: 0x12191f, accent: 0x42ffc0 },
    walkSpeed: 2.9,
    health: 135,
    armor: 25,
    bravery: 0.72,
    trust: 12,
    fear: 2,
    persuasionDifficulty: 0.82,
    bribe: { allowed: true, minimum: 900, greed: 0.36 },
    weapon: "taser",
    cash: [0, 40],
    dialogue: ["Your probability of survival is improving.", "The porcine hybrids violated the accord.", "Bring the power cell. Then we negotiate."],
  },
  area51Scientist: {
    id: "area51Scientist",
    label: "Range Scientist",
    occupation: "researcher",
    faction: "area51-research",
    colors: { skin: 0xc18a69, shirt: 0xd7d9d8, pants: 0x273039, accent: 0x5ee0ff },
    walkSpeed: 2.45,
    health: 82,
    bravery: 0.28,
    trust: 18,
    fear: 18,
    persuasionDifficulty: 0.68,
    bribe: { allowed: true, minimum: 750, greed: 0.7 },
    cash: [120, 480],
    dialogue: ["You did not see Hangar Seven.", "The craft is awake again.", "I can open one door. The rest is on you."],
  },
  detective: {
    id: "detective",
    label: "Detective",
    occupation: "police",
    isCop: true,
    colors: { skin: 0x8e5e49, shirt: 0xb7ac92, pants: 0x292b32, accent: 0x446b93 },
    walkSpeed: 3,
    chaseSpeed: 6.2,
    health: 135,
    armor: 45,
    bravery: 0.95,
    trust: 4,
    fear: 0,
    persuasionDifficulty: 0.96,
    bribe: { allowed: false, minimum: 1800, greed: 0, maxWantedLevel: 0 },
    weapon: "pistol",
    cash: [30, 120],
    dialogue: ["Your story has holes.", "I've been following this trail all night.", "Save it for the station."],
  },
});

export const VEHICLE_TYPES = deepFreeze({
  compact: {
    id: "compact",
    label: "Desert Compact",
    class: "compact",
    dimensions: { width: 1.72, length: 3.75, height: 1.48 },
    wheel: { radius: 0.35, width: 0.24 },
    maxHealth: 145,
    maxSpeed: 38,
    reverseSpeed: 12,
    acceleration: 17,
    brake: 28,
    handling: 2.35,
    grip: 0.88,
    seats: 4,
    value: 6500,
    spawnWeight: 23,
    colors: [0x36a8a0, 0xd5d0c2, 0xb34545, 0x303640],
  },
  sedan: {
    id: "sedan",
    label: "Strip Sedan",
    class: "sedan",
    dimensions: { width: 1.9, length: 4.65, height: 1.5 },
    wheel: { radius: 0.38, width: 0.26 },
    maxHealth: 185,
    maxSpeed: 43,
    reverseSpeed: 13,
    acceleration: 15,
    brake: 27,
    handling: 1.9,
    grip: 0.9,
    seats: 4,
    value: 12000,
    spawnWeight: 26,
    colors: [0x5c6470, 0xe5e2db, 0x244d7a, 0x7b263e],
  },
  taxi: {
    id: "taxi",
    label: "Vegas Taxi",
    class: "service",
    dimensions: { width: 1.92, length: 4.72, height: 1.54 },
    wheel: { radius: 0.38, width: 0.26 },
    maxHealth: 195,
    maxSpeed: 41,
    reverseSpeed: 13,
    acceleration: 14,
    brake: 26,
    handling: 1.82,
    grip: 0.89,
    seats: 4,
    value: 10500,
    spawnWeight: 10,
    colors: [0xf1b72d],
    roofSign: true,
  },
  muscle: {
    id: "muscle",
    label: "Neon Muscle",
    class: "muscle",
    dimensions: { width: 1.98, length: 4.58, height: 1.34 },
    wheel: { radius: 0.42, width: 0.31 },
    maxHealth: 215,
    maxSpeed: 52,
    reverseSpeed: 15,
    acceleration: 25,
    brake: 30,
    handling: 1.78,
    grip: 0.84,
    seats: 2,
    value: 28000,
    spawnWeight: 14,
    colors: [0xa31936, 0x17191e, 0xe16b24, 0x4c2b76],
  },
  sports: {
    id: "sports",
    label: "Mirage GT",
    class: "sports",
    dimensions: { width: 2.04, length: 4.42, height: 1.18 },
    wheel: { radius: 0.4, width: 0.32 },
    maxHealth: 165,
    maxSpeed: 66,
    reverseSpeed: 17,
    acceleration: 32,
    brake: 36,
    handling: 2.55,
    grip: 0.96,
    seats: 2,
    value: 88000,
    spawnWeight: 6,
    colors: [0xef2d56, 0x22b8d6, 0xf0d449, 0xf4f5f7, 0x15161c],
  },
  suv: {
    id: "suv",
    label: "Mojave SUV",
    class: "suv",
    dimensions: { width: 2.08, length: 4.92, height: 1.82 },
    wheel: { radius: 0.46, width: 0.32 },
    maxHealth: 280,
    maxSpeed: 45,
    reverseSpeed: 13,
    acceleration: 16,
    brake: 25,
    handling: 1.55,
    grip: 0.93,
    seats: 5,
    value: 36000,
    spawnWeight: 15,
    colors: [0x243b32, 0x3b414a, 0xc7c0ab, 0x623d2d],
  },
  policeCruiser: {
    id: "policeCruiser",
    label: "LVMPD Cruiser",
    class: "emergency",
    dimensions: { width: 1.98, length: 4.85, height: 1.56 },
    wheel: { radius: 0.4, width: 0.28 },
    maxHealth: 260,
    maxSpeed: 55,
    reverseSpeed: 16,
    acceleration: 24,
    brake: 33,
    handling: 2.18,
    grip: 0.96,
    seats: 4,
    value: 0,
    spawnWeight: 0,
    colors: [0x171a20],
    police: true,
    hasSiren: true,
  },
  limousine: {
    id: "limousine",
    label: "Aurelia Executive Limousine",
    class: "luxury",
    dimensions: { width: 2.05, length: 6.25, height: 1.48 },
    wheel: { radius: 0.41, width: 0.28 },
    maxHealth: 235,
    maxSpeed: 46,
    reverseSpeed: 12,
    acceleration: 13,
    brake: 25,
    handling: 1.42,
    grip: 0.92,
    seats: 6,
    value: 78000,
    spawnWeight: 2,
    maxFuel: 120,
    fuelBurnMultiplier: 1.22,
    colors: [0x101116, 0xf0f1f3, 0x34283d],
  },
  streetMotorcycle: {
    id: "streetMotorcycle",
    label: "Neon Street Motorcycle",
    class: "motorcycle",
    dimensions: { width: 0.82, length: 2.18, height: 1.18 },
    wheel: { radius: 0.36, width: 0.13 },
    maxHealth: 92,
    maxSpeed: 59,
    reverseSpeed: 7,
    acceleration: 35,
    brake: 34,
    handling: 3.1,
    grip: 0.9,
    seats: 2,
    value: 16000,
    spawnWeight: 5,
    maxFuel: 52,
    fuelBurnMultiplier: 0.62,
    colors: [0x191b20, 0xc72942, 0x2b6cca, 0xe8e9eb],
  },
  motorcycle: {
    id: "motorcycle",
    label: "Neon Street Motorcycle",
    class: "motorcycle",
    dimensions: { width: 0.82, length: 2.18, height: 1.18 },
    wheel: { radius: 0.36, width: 0.13 },
    maxHealth: 92,
    maxSpeed: 59,
    reverseSpeed: 7,
    acceleration: 35,
    brake: 34,
    handling: 3.1,
    grip: 0.9,
    seats: 2,
    value: 16000,
    spawnWeight: 0,
    maxFuel: 52,
    fuelBurnMultiplier: 0.62,
    colors: [0x191b20, 0xc72942, 0x2b6cca, 0xe8e9eb],
  },
  dirtBike: {
    id: "dirtBike",
    label: "Mojave Dirt Bike",
    class: "motorcycle",
    dimensions: { width: 0.84, length: 2.14, height: 1.28 },
    wheel: { radius: 0.39, width: 0.12 },
    maxHealth: 104,
    maxSpeed: 48,
    reverseSpeed: 6,
    acceleration: 32,
    brake: 31,
    handling: 3.25,
    grip: 0.86,
    seats: 2,
    value: 12500,
    spawnWeight: 4,
    maxFuel: 46,
    fuelBurnMultiplier: 0.72,
    offRoad: true,
    colors: [0xcf4c24, 0x2484b8, 0xe2dfd5, 0x2d342b],
  },
  bicycle: {
    id: "bicycle",
    label: "Strip Cruiser Bicycle",
    class: "bicycle",
    dimensions: { width: 0.68, length: 1.86, height: 1.22 },
    wheel: { radius: 0.34, width: 0.065 },
    maxHealth: 48,
    maxSpeed: 14,
    reverseSpeed: 3,
    acceleration: 8,
    brake: 14,
    handling: 3,
    grip: 0.82,
    seats: 1,
    value: 850,
    spawnWeight: 3,
    maxFuel: 100,
    fuelBurnMultiplier: 0,
    fuelType: "stamina",
    colors: [0x272a2f, 0x2d8a78, 0xd9d8d2, 0x8b2f40],
  },
  atv: {
    id: "atv",
    label: "Desert Trail ATV",
    class: "offroad",
    dimensions: { width: 1.2, length: 2.18, height: 1.18 },
    wheel: { radius: 0.35, width: 0.2 },
    maxHealth: 138,
    maxSpeed: 34,
    reverseSpeed: 9,
    acceleration: 24,
    brake: 25,
    handling: 2.65,
    grip: 0.91,
    seats: 2,
    value: 9800,
    spawnWeight: 4,
    maxFuel: 58,
    fuelBurnMultiplier: 0.78,
    offRoad: true,
    colors: [0x6d5b36, 0x2e4637, 0x9e3126, 0x30343a],
  },
  duneBuggy: {
    id: "duneBuggy",
    label: "Red Rock Dune Buggy",
    class: "offroad",
    dimensions: { width: 1.78, length: 3.2, height: 1.55 },
    wheel: { radius: 0.48, width: 0.3 },
    maxHealth: 168,
    maxSpeed: 46,
    reverseSpeed: 12,
    acceleration: 26,
    brake: 27,
    handling: 2.45,
    grip: 0.87,
    seats: 2,
    value: 24500,
    spawnWeight: 3,
    maxFuel: 72,
    fuelBurnMultiplier: 1.04,
    offRoad: true,
    colors: [0xd17a25, 0x2d887a, 0x30343a, 0xc6b276],
  },
  offroadPickup: {
    id: "offroadPickup",
    label: "Mojave Trail Pickup",
    class: "offroad",
    dimensions: { width: 2.08, length: 5.25, height: 1.93 },
    wheel: { radius: 0.5, width: 0.34 },
    maxHealth: 330,
    maxSpeed: 47,
    reverseSpeed: 14,
    acceleration: 18,
    brake: 27,
    handling: 1.6,
    grip: 0.95,
    seats: 5,
    value: 44000,
    spawnWeight: 5,
    maxFuel: 126,
    fuelBurnMultiplier: 1.18,
    offRoad: true,
    colors: [0x514736, 0x3b4447, 0xb9b3a4, 0x6a2e2b],
  },
  offroadSuv: {
    id: "offroadSuv",
    label: "Red Rock 4x4",
    class: "offroad",
    dimensions: { width: 2.1, length: 4.9, height: 1.92 },
    wheel: { radius: 0.49, width: 0.33 },
    maxHealth: 315,
    maxSpeed: 48,
    reverseSpeed: 14,
    acceleration: 19,
    brake: 28,
    handling: 1.68,
    grip: 0.96,
    seats: 5,
    value: 52000,
    spawnWeight: 5,
    maxFuel: 118,
    fuelBurnMultiplier: 1.15,
    offRoad: true,
    colors: [0x26372e, 0x3b4148, 0xd0c8b8, 0x714637],
  },
  utilityVan: {
    id: "utilityVan",
    label: "Valley Utility Van",
    class: "service",
    dimensions: { width: 2.05, length: 5.35, height: 2.32 },
    wheel: { radius: 0.44, width: 0.29 },
    maxHealth: 275,
    maxSpeed: 39,
    reverseSpeed: 12,
    acceleration: 12,
    brake: 24,
    handling: 1.35,
    grip: 0.9,
    seats: 3,
    value: 31000,
    spawnWeight: 7,
    maxFuel: 132,
    fuelBurnMultiplier: 1.1,
    colors: [0xe7e8e6, 0x3b4953, 0xc6b370, 0x294d73],
  },
  airportShuttle: {
    id: "airportShuttle",
    label: "Desert Sky Airport Shuttle",
    class: "service",
    dimensions: { width: 2.22, length: 6.15, height: 2.55 },
    wheel: { radius: 0.47, width: 0.31 },
    maxHealth: 310,
    maxSpeed: 37,
    reverseSpeed: 11,
    acceleration: 11,
    brake: 23,
    handling: 1.18,
    grip: 0.91,
    seats: 12,
    value: 56000,
    spawnWeight: 4,
    maxFuel: 150,
    fuelBurnMultiplier: 1.3,
    colors: [0xe4e7e7, 0x2b6680, 0x8b3034],
  },
  policeSuv: {
    id: "policeSuv",
    label: "Metro Pursuit SUV",
    class: "emergency",
    dimensions: { width: 2.1, length: 5.05, height: 1.92 },
    wheel: { radius: 0.49, width: 0.33 },
    maxHealth: 350,
    maxSpeed: 54,
    reverseSpeed: 15,
    acceleration: 21,
    brake: 31,
    handling: 1.8,
    grip: 0.97,
    seats: 5,
    value: 0,
    spawnWeight: 0,
    maxFuel: 125,
    fuelBurnMultiplier: 1.22,
    offRoad: true,
    colors: [0x15181d],
    police: true,
    hasSiren: true,
  },
});

export const MISSIONS = deepFreeze([
  {
    id: "wash-cache",
    title: "Below the Neon",
    description: "Follow a tunnel runner into the flood-control wash and recover a hidden cache.",
    giver: "tunnelRunner",
    recommendedRole: "drifter",
    objectives: [
      { type: "talk", target: "tunnelRunner", count: 1 },
      { type: "enterZone", target: "drainTunnels", count: 1 },
      { type: "collect", target: "contraband", count: 2 },
      { type: "escape", target: "tunnelExit", count: 1 },
    ],
    rewards: { cash: 900, reputation: 12, item: "lockpick" },
    failOnArrest: true,
  },
  {
    id: "house-favor",
    title: "House Favor",
    description: "Persuade a VIP to return to the casino without causing a scene.",
    giver: "casinoDealer",
    recommendedRole: "hustler",
    objectives: [
      { type: "find", target: "highRoller", count: 1 },
      { type: "persuade", target: "highRoller", count: 1 },
      { type: "escort", target: "casinoEntrance", count: 1 },
    ],
    rewards: { cash: 700, chips: 300, reputation: 14 },
    failOnViolence: true,
  },
  {
    id: "desert-airmail",
    title: "Desert Airmail",
    description: "Fly a sealed package from the municipal strip to a dry-lake drop point.",
    giver: "mechanic",
    recommendedRole: "pilot",
    objectives: [
      { type: "enterVehicle", target: "plane", count: 1 },
      { type: "takeoff", target: "airportRunway", count: 1 },
      { type: "flyThrough", target: "airCheckpoint", count: 3 },
      { type: "land", target: "dryLake", count: 1 },
    ],
    rewards: { cash: 1450, reputation: 16 },
    timeLimitSeconds: 240,
  },
  {
    id: "hot-wheels",
    title: "Hot Wheels",
    description: "Recover a stolen sports car and lose the police before delivering it intact.",
    giver: "mechanic",
    recommendedRole: "wheelman",
    objectives: [
      { type: "enterVehicle", target: "sports", count: 1 },
      { type: "reachWantedLevel", target: 2, count: 1 },
      { type: "loseWanted", target: 0, count: 1 },
      { type: "deliverVehicle", target: "garage", count: 1, minHealth: 70 },
    ],
    rewards: { cash: 1700, reputation: 18, vehicleDiscount: 0.12 },
    failOnVehicleDestroyed: true,
  },
  {
    id: "price-of-silence",
    title: "The Price of Silence",
    description: "Talk or pay your way past witnesses before an illicit handoff is reported.",
    giver: "local",
    recommendedRole: "hustler",
    objectives: [
      { type: "collect", target: "contraband", count: 1 },
      { type: "persuadeOrBribe", target: "witness", count: 2 },
      { type: "deliver", target: "casinoLoadingBay", count: 1 },
    ],
    rewards: { cash: 1200, reputation: 15 },
    timeLimitSeconds: 180,
  },
  {
    id: "lucky-streak",
    title: "Lucky Streak",
    description: "Turn a modest stack of chips into a casino-night target without going broke.",
    giver: "highRoller",
    recommendedRole: "highRoller",
    objectives: [
      { type: "buyChips", target: "casinoCashier", count: 250 },
      { type: "gamble", target: "anyTable", count: 3 },
      { type: "chipBalance", target: 600, count: 1 },
      { type: "cashOut", target: "casinoCashier", count: 1 },
    ],
    rewards: { cash: 650, reputation: 10, casinoComp: 200 },
    failBelowChipBalance: 0,
  },
]);

const normalizeSeed = (seed) => {
  if (typeof seed === "number" && Number.isFinite(seed)) return seed >>> 0;
  const text = String(seed ?? GAME_CONFIG.seed);
  let hash = 2166136261;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  hash += hash << 13;
  hash ^= hash >>> 7;
  hash += hash << 3;
  hash ^= hash >>> 17;
  hash += hash << 5;
  return hash >>> 0;
};

/**
 * Creates a deterministic RNG with helpers for procedural placement and loot.
 * Calling the function directly returns a float in [0, 1).
 */
export function createSeededRng(seed = GAME_CONFIG.seed) {
  const initialSeed = normalizeSeed(seed) || 0x6d2b79f5;
  let state = initialSeed;

  const rng = () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let value = state;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };

  rng.float = rng;
  rng.range = (min = 0, max = 1) => {
    const low = Math.min(min, max);
    const high = Math.max(min, max);
    return low + (high - low) * rng();
  };
  rng.int = (min, max) => {
    const first = Number(min ?? 0);
    const second = max === undefined ? 0 : Number(max);
    const low = Math.ceil(Math.min(first, second));
    const high = Math.floor(Math.max(first, second));
    return low + Math.floor(rng() * (high - low + 1));
  };
  rng.chance = (probability) => rng() < Math.max(0, Math.min(1, probability));
  rng.pick = (items) => (items?.length ? items[rng.int(0, items.length - 1)] : undefined);
  rng.shuffle = (items) => {
    const result = Array.from(items ?? []);
    for (let index = result.length - 1; index > 0; index -= 1) {
      const swapIndex = rng.int(0, index);
      [result[index], result[swapIndex]] = [result[swapIndex], result[index]];
    }
    return result;
  };
  rng.weighted = (items, getWeight = (item) => item?.weight ?? 1) => {
    if (!items?.length) return undefined;
    const weights = items.map((item) => Math.max(0, Number(getWeight(item)) || 0));
    const total = weights.reduce((sum, weight) => sum + weight, 0);
    if (total <= 0) return rng.pick(items);
    let roll = rng() * total;
    for (let index = 0; index < items.length; index += 1) {
      roll -= weights[index];
      if (roll <= 0) return items[index];
    }
    return items[items.length - 1];
  };
  rng.getState = () => state >>> 0;
  rng.setState = (nextState) => {
    state = normalizeSeed(nextState) || initialSeed;
    return rng;
  };
  rng.fork = (salt) => createSeededRng(`${initialSeed}:${String(salt)}`);

  return rng;
}
